package com.github.connorlobb.AdvancedGeology.crafting;

import com.github.connorlobb.AdvancedGeology.init.ModBlocks;
import com.github.connorlobb.AdvancedGeology.init.ModItems;

import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import cpw.mods.fml.common.registry.GameRegistry;

public class Recipes {
	public static void init() {
		//AdvancedGeology Shaped Crafting Recipes
		GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.fossilAnalyzer), new Object[] {"ABA", "ACA", "ADA", 'A', Items.iron_ingot, 'B', Blocks.glass_pane, 'C', ModItems.fossil, 'D', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.bricksAndesite,4), new Object[] {"AA", "AA", 'A', ModBlocks.stoneAndesite});
		GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.bricksBasalt,4), new Object[] {"AA", "AA", 'A', ModBlocks.stoneBasalt});
		GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.bricksChalk,4), new Object[] {"AA", "AA", 'A', ModBlocks.stoneChalk});
		GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.bricksChert,4), new Object[] {"AA", "AA", 'A', ModBlocks.stoneChert});
		GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.bricksClaystone,4), new Object[] {"AA", "AA", 'A', ModBlocks.stoneClaystone});
		GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.bricksConglomerate,4), new Object[] {"AA", "AA", 'A', ModBlocks.stoneConglomerate});
		GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.bricksDacite,4), new Object[] {"AA", "AA", 'A', ModBlocks.stoneDacite});
		GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.bricksDiorite,4), new Object[] {"AA", "AA", 'A', ModBlocks.stoneDiorite});
		GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.bricksDolomite,4), new Object[] {"AA", "AA", 'A', ModBlocks.stoneDolomite});
		GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.bricksGabbro,4), new Object[] {"AA", "AA", 'A', ModBlocks.stoneGabbro});
		GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.bricksGneiss,4), new Object[] {"AA", "AA", 'A', ModBlocks.stoneGneiss});
		GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.bricksGranite,4), new Object[] {"AA", "AA", 'A', ModBlocks.stoneGranite});
		GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.bricksLimestone,4), new Object[] {"AA", "AA", 'A', ModBlocks.stoneLimestone});
		GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.bricksMarble,4), new Object[] {"AA", "AA", 'A', ModBlocks.stoneMarble});
		//AdvancedGeology Smelting Recipes
		GameRegistry.addSmelting(ModBlocks.fossilOre, new ItemStack(ModItems.fossil), 0.8F);
		GameRegistry.addSmelting(ModBlocks.cobblestoneAndesite, new ItemStack(ModBlocks.stoneAndesite), 0.8F);
		GameRegistry.addSmelting(ModBlocks.cobblestoneBasalt, new ItemStack(ModBlocks.stoneBasalt), 0.8F);
		GameRegistry.addSmelting(ModBlocks.cobblestoneChalk, new ItemStack(ModBlocks.stoneChalk), 0.8F);
		GameRegistry.addSmelting(ModBlocks.cobblestoneChert, new ItemStack(ModBlocks.stoneChert), 0.8F);
		GameRegistry.addSmelting(ModBlocks.cobblestoneClaystone, new ItemStack(ModBlocks.stoneClaystone), 0.8F);
		GameRegistry.addSmelting(ModBlocks.cobblestoneConglomerate, new ItemStack(ModBlocks.stoneConglomerate), 0.8F);
		GameRegistry.addSmelting(ModBlocks.cobblestoneDacite, new ItemStack(ModBlocks.stoneDacite), 0.8F);
		GameRegistry.addSmelting(ModBlocks.cobblestoneDiorite, new ItemStack(ModBlocks.stoneDiorite), 0.8F);
		GameRegistry.addSmelting(ModBlocks.cobblestoneDolomite, new ItemStack(ModBlocks.stoneDolomite), 0.8F);
		GameRegistry.addSmelting(ModBlocks.cobblestoneGabbro, new ItemStack(ModBlocks.stoneGabbro), 0.8F);
		GameRegistry.addSmelting(ModBlocks.cobblestoneGneiss, new ItemStack(ModBlocks.stoneGneiss), 0.8F);
		GameRegistry.addSmelting(ModBlocks.cobblestoneGranite, new ItemStack(ModBlocks.stoneGranite), 0.8F);
		GameRegistry.addSmelting(ModBlocks.cobblestoneLimestone, new ItemStack(ModBlocks.stoneLimestone), 0.8F);
		GameRegistry.addSmelting(ModBlocks.cobblestoneMarble, new ItemStack(ModBlocks.stoneMarble), 0.8F);
		//GameRegistry.addSmelting(ModBlocks.cobblestonePhyllite, new ItemStack(ModBlocks.stonePhyllite), 0.8F);
		//GameRegistry.addSmelting(ModBlocks.cobblestoneQuartzite, new ItemStack(ModBlocks.stoneQuartzite), 0.8F);
		//GameRegistry.addSmelting(ModBlocks.cobblestoneRhyolite, new ItemStack(ModBlocks.stoneRhyolite), 0.8F);
		//GameRegistry.addSmelting(ModBlocks.cobblestoneRockSalt, new ItemStack(ModBlocks.stoneRockSalt), 0.8F);
		//GameRegistry.addSmelting(ModBlocks.cobblestoneSchist, new ItemStack(ModBlocks.stoneSchist), 0.8F);
		//GameRegistry.addSmelting(ModBlocks.cobblestoneShale, new ItemStack(ModBlocks.stoneShale), 0.8F);
		//GameRegistry.addSmelting(ModBlocks.cobblestoneSlate, new ItemStack(ModBlocks.stoneSlate), 0.8F);
		//Lever recipe makeup
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneAndesite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneBasalt});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneChalk});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneChert});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneClaystone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneConglomerate});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneDacite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneDiorite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneDolomite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneGabbro});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneGneiss});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneGranite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneLimestone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneMarble});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestonePhyllite});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneQuartzite});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneRhyolite});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneRockSalt});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneSchist});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneShale});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.lever), new Object[] {"A", "B", 'A', Items.stick, 'B', ModBlocks.cobblestoneSlate});
		//Stone How recipe makeup
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneAndesite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneBasalt, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneChalk, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneChert, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneClaystone, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneConglomerate, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneDacite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneDiorite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneDolomite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneGabbro, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneGneiss, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneGranite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneLimestone, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneMarble, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestonePhyllite, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneQuartzite, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneRhyolite, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneRockSalt, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneSchist, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneShale, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_hoe), new Object[] {"AA", " B", " B", 'A', ModBlocks.cobblestoneSlate, 'B', Items.stick});
		//Brewing Stand recipe makeup
		GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneAndesite});
		GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneBasalt});
		GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneChalk});
		GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneChert});
		GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneClaystone});
		GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneConglomerate});
		GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneDacite});
		GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneDiorite});
		GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneDolomite});
		GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneGabbro});
		GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneGneiss});
		GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneGranite});
		GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneLimestone});
		GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneMarble});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestonePhyllite});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneQuartzite});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneRhyolite});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneRockSalt});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneSchist});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneShale});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.brewing_stand), new Object[] {" A ", "BBB", 'A', Items.blaze_rod, 'B', ModBlocks.cobblestoneSlate});
		//Stone Axe recipe makeup
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneAndesite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneBasalt, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneChalk, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneChert, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneClaystone, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneConglomerate, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneDacite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneDiorite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneDolomite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneGabbro, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneGneiss, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneGranite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneLimestone, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneMarble, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestonePhyllite, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneQuartzite, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneRhyolite, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneRockSalt, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneSchist, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneShale, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_axe), new Object[] {"AA", "AB", " B", 'A', ModBlocks.cobblestoneSlate, 'B', Items.stick});
		//Stone Shovel recipe makeup
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneAndesite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneBasalt, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneChalk, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneChert, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneClaystone, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneConglomerate, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneDacite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneDiorite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneDolomite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneGabbro, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneGneiss, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneGranite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneLimestone, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneMarble, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestonePhyllite, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneQuartzite, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneRhyolite, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneRockSalt, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneSchist, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneShale, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_shovel), new Object[] {"A", "B", "B", 'A', ModBlocks.cobblestoneSlate, 'B', Items.stick});
		//Piston recipe makeup
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneAndesite, 'C', Items.iron_ingot, 'D', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneBasalt, 'C', Items.iron_ingot, 'D', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneChalk, 'C', Items.iron_ingot, 'D', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneChert, 'C', Items.iron_ingot, 'D', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneClaystone, 'C', Items.iron_ingot, 'D', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneConglomerate, 'C', Items.iron_ingot, 'D', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneDacite, 'C', Items.iron_ingot, 'D', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneDiorite, 'C', Items.iron_ingot, 'D', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneDolomite, 'C', Items.iron_ingot, 'D', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneGabbro, 'C', Items.iron_ingot, 'D', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneGneiss, 'C', Items.iron_ingot, 'D', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneGranite, 'C', Items.iron_ingot, 'D', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneLimestone, 'C', Items.iron_ingot, 'D', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneMarble, 'C', Items.iron_ingot, 'D', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestonePhyllite, 'C', Items.iron_ingot, 'D', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneQuartzite, 'C', Items.iron_ingot, 'D', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneRhyollite, 'C', Items.iron_ingot, 'D', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneRockSalt, 'C', Items.iron_ingot, 'D', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneSchist, 'C', Items.iron_ingot, 'D', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneShale, 'C', Items.iron_ingot, 'D', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.piston), new Object[] {"AAA", "BCB", "BDB", 'A', Blocks.planks, 'B', ModBlocks.cobblestoneSlate, 'C', Items.iron_ingot, 'D', Items.redstone});
		//Stone Sword recipe makeup
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneAndesite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneBasalt, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneChalk, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneChert, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneClaystone, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneConglomerate, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneDacite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneDiorite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneDolomite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneGabbro, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneGneiss, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneGranite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneLimestone, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneMarble, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestonePhyllite, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneQuartzite, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneRhyolite, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneRockSalt, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneSchist, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneShale, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_sword), new Object[] {"A", "A", "B", 'A', ModBlocks.cobblestoneSlate, 'B', Items.stick});
		//Dispenser recipe makeup
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneAndesite, 'B', Items.bow, 'C', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneBasalt, 'B', Items.bow, 'C', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneChalk, 'B', Items.bow, 'C', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneChert, 'B', Items.bow, 'C', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneClaystone, 'B', Items.bow, 'C', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneConglomerate, 'B', Items.bow, 'C', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneDacite, 'B', Items.bow, 'C', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneDiorite, 'B', Items.bow, 'C', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneDolomite, 'B', Items.bow, 'C', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneGabbro, 'B', Items.bow, 'C', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneGneiss, 'B', Items.bow, 'C', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneGranite, 'B', Items.bow, 'C', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneLimestone, 'B', Items.bow, 'C', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneMarble, 'B', Items.bow, 'C', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestonePhyllite, 'B', Items.bow, 'C', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneQuartzite, 'B', Items.bow, 'C', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneRhyolite, 'B', Items.bow, 'C', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneRockSalt, 'B', Items.bow, 'C', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneSchist, 'B', Items.bow, 'C', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneShale, 'B', Items.bow, 'C', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.dispenser), new Object[] {"AAA", "ABA", "ACA", 'A', ModBlocks.cobblestoneSlate, 'B', Items.bow, 'C', Items.redstone});
		//Furnace recipe makeup
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneAndesite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneBasalt});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneChalk});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneChert});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneClaystone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneConglomerate});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneDacite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneDiorite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneDolomite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneGabbro});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneGneiss});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneGranite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneLimestone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneMarble});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestonePhyllite});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneQuartzite});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneRhyolite});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneRockSalt});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneSchist});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneShale});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.furnace), new Object[] {"AAA", "A A", "AAA", 'A', ModBlocks.cobblestoneSlate});
		//Dropper recipe makeup
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneAndesite, 'B', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneBasalt, 'B', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneChalk, 'B', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneChert, 'B', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneClaystone, 'B', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneConglomerate, 'B', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneDacite, 'B', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneDiorite, 'B', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneDolomite, 'B', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneGabbro, 'B', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneGneiss, 'B', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneGranite, 'B', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneLimestone, 'B', Items.redstone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneMarble, 'B', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestonePhyllite, 'B', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneQuartzite, 'B', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneRhyolite, 'B', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneRockSalt, 'B', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneSchist, 'B', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneShale, 'B', Items.redstone});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.dropper), new Object[] {"AAA", "A A", "ABA", 'A', ModBlocks.cobblestoneSlate, 'B', Items.redstone});
		//Stone Pickaxe recipe makeup
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneAndesite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneBasalt, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneChalk, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneChert, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneClaystone, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneConglomerate, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneDacite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneDiorite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneDolomite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneGabbro, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneGneiss, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneGranite, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneLimestone, 'B', Items.stick});
		GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneMarble, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestonePhyllite, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneQuartzite, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneRhyolite, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneRockSalt, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneSchist, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneShale, 'B', Items.stick});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.stone_pickaxe), new Object[] {"AAA", " B ", " B ", 'A', ModBlocks.cobblestoneSlate, 'B', Items.stick});
		//Redstone Comparator recipe makeup
		GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneAndesite});
		GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneBasalt});
		GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneChalk});
		GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneChert});
		GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneClaystone});
		GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneConglomerate});
		GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneDacite});
		GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneDiorite});
		GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneDolomite});
		GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneGabbro});
		GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneGneiss});
		GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneGranite});
		GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneLimestone});
		GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneMarble});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stonePhyllite});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneQuartzite});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneRhyolite});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneRockSalt});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneSchist});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneShale});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.comparator), new Object[] {" A ", "ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.quartz, 'C', ModBlocks.stoneSlate});
		//Stone Button recipe makeup
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneAndesite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneBasalt});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneChalk});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneChert});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneClaystone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneConglomerate});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneDacite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneDiorite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneDolomite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneGabbro});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneGneiss});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneGranite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneLimestone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneMarble});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stonePhyllite});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneQuartzite});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneRhyolite});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneRockSalt});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneSchist});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneShale});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_button), new Object[] {"A", 'A', ModBlocks.stoneSlate});
		//Stone Pressure Plate recipe makeup
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneAndesite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneBasalt});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneChalk});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneChert});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneClaystone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneConglomerate});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneDacite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneDiorite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneDolomite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneGabbro});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneGneiss});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneGranite});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneLimestone});
		GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneMarble});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stonePhyllite});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneQuartzite});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneRhyolite});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneRockSalt});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneSchist});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneShale});
		//GameRegistry.addShapedRecipe(new ItemStack(Blocks.stone_pressure_plate), new Object[] {"AA", 'A', ModBlocks.stoneSlate});
		//Redstone Repeater recipe makeup
		GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneAndesite});
		GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneBasalt});
		GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneChalk});
		GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneChert});
		GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneClaystone});
		GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneConglomerate});
		GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneDacite});
		GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneDiorite});
		GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneDolomite});
		GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneGabbro});
		GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneGneiss});
		GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneGranite});
		GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneLimestone});
		GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneMarble});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stonePhyllite});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneQuartzite});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneRhyolite});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneRockSalt});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneSchist});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneShale});
		//GameRegistry.addShapedRecipe(new ItemStack(Items.repeater), new Object[] {"ABA", "CCC", 'A', Blocks.redstone_torch, 'B', Items.redstone, 'C', ModBlocks.stoneSlate});
	}
}